server:
  port: 8080

spring:
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    url: jdbc:mysql://localhost/siseoj_test?serverTimezone=Asia/Shanghai
    username: root
    password: 1234,abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 扩展插件
      # 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      filters: stat, wall
      # 最大连接池数量
      maxActive: 20
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 5
      # 获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 最小连接池数量
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
      validationQuery: select count(1) from 'table'
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 是否缓存preparedStatement，即PSCache
      poolPreparedStatements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-open-prepared-statements: -1

  fastjson:
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    database: 0
    host: 106.52.183.73
    port: 6379
    password: 1234,abcd
    timeout: 5000
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-active: 50
  # 邮寄配置
  mail:
    # smtp主机
    host: smtp.qq.com
    # 服务协议
    protocol: smtp
    default-encoding: UTF-8
    # 发送邮箱的账户
    username: saykuray@qq.com
    # 授权码
    password: vmjpsysytpdweagg
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# mybatis-plus
mybatis-plus:
  global-config:
    # 不显示banner
    banner: false
    db-config:
      # 数据库自增
      id-type: auto
      # 下划线转换
      table-underline: true
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:config/logback-spring.xml

#邮箱验证有效时间/分钟
code:
  expire: 10

# 登录相关配置
login:
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    heigth: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

# jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

# 是否开启 swagger-ui
swagger:
  enabled: true

# OJ配置
oj:
  config:
    logHandler:
      enable: false
    exceptionLogHandler:
      enable: false
  judge:
    url: http://106.52.183.73:8100
  fileServer:
    url: http://106.52.183.73:8200

# 文件存储路径
file:
  mac:
    file: ~/file/
    avatar: ~/avatar/
  linux:
    file: /home/siseoj/file/
    avatar: /home/siseoj/avatar/
  windows:
    file: D:\siseoj\file\
    avatar: D:\siseoj\avatar\
  # 文件大小 M
  maxSize: 100
  avatarMaxSize: 5

# 非对称加密，前端公钥加密，后端私钥解密
rsa:
  private_key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAIJkDEHUe9gdHopthTIa1N5LJUorsrdSii7g7cN3+heO7d4sKj8dFnTxsyQ2PxfNU5WBSIgOoy+6RW3RcyW/LNePPeyqOhJPoi9aUEzIZrgH7Qp3yGq27V+tdvUVRgKYirWA2Yt8Ox4QAQ2xDlLf7zoyePmgx6UQLpXPhkmx20UNAgMBAAECgYBT1bHPzaeGz0oopLwj9/5voo8qPihdGBPCilo0+HnzFbG4zFqpU7FxpUmR+dLdIeYg1QvmdsrTUAd90VIgredNEBzuuF2VNAB5FeBPDvo2tLAHVZGThI4uExVGZHRSUfXjs9B5T/oQdaRcdlyebGnqpiZoMIN7MNIAF/WtkROi4QJBANG839/3S05lWoODrr+Y2kxeByuwhXhk8KtQTqcjojg8OFRcFTVVShS1osczTlaPDYNKPBZJ7GhhMysUzupHkRkCQQCfJr1ml3vGgiz8NyTmomRxjKrqGnodlnhYP+1TcMyjc2xp21nOBmVOthItdlr6PibdGB0MDSt8NDM/jNcRFQ4VAkEAyur/dkJde3WXwtGuSfRqj6QRL/XSzA5swnIqBo71LY8luIh2hGkGCU9KM4ux6RDyM+mohK/0p3AS/0Vcg1HGUQJBAIN923Ce6eoJ9abw3LEdLMXQRgojlA9MGeQ39RpCkSDepY0UaS9ag2sz7PLY3bPxk+SKHr2tR+dXrZvs/mgjsD0CQQCg9w5JCSboHLojtCp5S5hgzZmIdxOXvYpHXemke+y9GjHD9TAec//mCvWiw0lRvEo9xN1Ghm7mYHCIoulUbRPl
  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCZAxB1HvYHR6KbYUyGtTeSyVKK7K3Uoou4O3Dd/oXju3eLCo/HRZ08bMkNj8XzVOVgUiIDqMvukVt0XMlvyzXjz3sqjoST6IvWlBMyGa4B+0Kd8hqtu1frXb1FUYCmIq1gNmLfDseEAENsQ5S3+86Mnj5oMelEC6Vz4ZJsdtFDQIDAQAB